### ISSUE TITLE
No such file or directory: 'downloads/mixs6_core.tsv'

### ISSUE THREAD

**Issue by turbomam** [cmungall/mixs-source#4]
I'm just making this for the first time! The download to `downloads/mixs6.tsv` works, but some subsequent step can't find `downloads/mixs6_core.tsv` 

```Bash
pipenv run python -m gsctools.mixs_converter
```

> Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/MAM/Documents/gitrepos/mixs-source/gsctools/mixs_converter.py", line 495, in <module>
    cli()
  File "/Users/MAM/.local/share/virtualenvs/mixs-source-ag2AQfeD/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/MAM/.local/share/virtualenvs/mixs-source-ag2AQfeD/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/MAM/.local/share/virtualenvs/mixs-source-ag2AQfeD/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/MAM/.local/share/virtualenvs/mixs-source-ag2AQfeD/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/MAM/Documents/gitrepos/mixs-source/gsctools/mixs_converter.py", line 491, in cli
    cv.convert_and_save('model/schema/mixs.yaml')
  File "/Users/MAM/Documents/gitrepos/mixs-source/gsctools/mixs_converter.py", line 144, in convert_and_save
    obj = self.convert()
  File "/Users/MAM/Documents/gitrepos/mixs-source/gsctools/mixs_converter.py", line 271, in convert
    core_df = pd.read_csv(self.core_filename, sep="\t").fillna("").applymap(trim_strings)
  File "/Users/MAM/.local/share/virtualenvs/mixs-source-ag2AQfeD/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/Users/MAM/.local/share/virtualenvs/mixs-source-ag2AQfeD/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/MAM/.local/share/virtualenvs/mixs-source-ag2AQfeD/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/MAM/.local/share/virtualenvs/mixs-source-ag2AQfeD/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/Users/MAM/.local/share/virtualenvs/mixs-source-ag2AQfeD/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/Users/MAM/.local/share/virtualenvs/mixs-source-ag2AQfeD/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/Users/MAM/.local/share/virtualenvs/mixs-source-ag2AQfeD/lib/python3.9/site-packages/pandas/io/parsers/base_parser.py", line 222, in _open_handles
    self.handles = get_handle(
  File "/Users/MAM/.local/share/virtualenvs/mixs-source-ag2AQfeD/lib/python3.9/site-packages/pandas/io/common.py", line 702, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'downloads/mixs6_core.tsv'

**Comment by turbomam** [comment]
`make downloads/mixs6_core.tsv` fixes the above, but ...

**Comment by turbomam** [comment]
How should I interpret this, from `downloads/README.md`

> @only1chunts uploaded new clean versions of the v6 checklist and package TSV files
MIxSv6_checklists_14Sep2021_CIH.tsv MIxSv6_packages_14Sep2021_CIH.tsv

I don't see that file in the downloads folder.

BTW Should I be using this repo or https://github.com/GenomicsStandardsConsortium/mixs ?

**Comment by only1chunts** [comment]
Hi, apparently there is a script somewhere that will actually take the mixs google sheet and create the relevant tsv files in that download folder, I was not aware of that script when I manually uploaded some new TSV files on 14th Sept, you can ignore those files even if you find them!
@cmungall should be able to help with the script to parse the google sheet, but the plan is to not do that until the next RDF call on 11Oct as I will have completed all the v6 changes by then!

**Comment by turbomam** [comment]
Thanks @only1chunts . I'm going to remove the remark I mentioned above in `downloads/README.md` because the Makefile does a good job of pulling all of the relevant Google Sheets now.
